// DO NOT EDIT
// This file is automatically generated!
// $ smg.shen rtl/SMG/seq.smg
//
// https://github.com/sam-falvo/smg

module Sequencer(
	input 	xt3,
	input 	xt2,
	input 	xt1,
	input 	xt0,
	input [31:0]	ir,
	input 	iack_i,
	input 	ft0,
	input 	rst,
	output 	sx32_en,
	output 	pc_alu,
	output 	xt3_o,
	output 	and_en,
	output 	rsh_en,
	output 	xor_en,
	output 	ltu_en,
	output 	lts_en,
	output 	invB_en,
	output 	cflag_i,
	output 	lsh_en,
	output 	sum_en,
	output 	alub_imm12i,
	output 	alub_rdat,
	output 	alua_rdat,
	output 	rwe_o,
	output 	rdat_pc,
	output 	rdat_alu,
	output 	ra_ird,
	output 	ra_ir2,
	output 	ra_ir1,
	output 	xt2_o,
	output 	xt1_o,
	output 	jammed_o,
	output 	xt0_o,
	output 	ir_idat,
	output 	pc_pcPlus4,
	output 	isiz_2,
	output 	iadr_pc,
	output 	pc_mbvec,
	output 	ft0_o
);
wire  useAlu2;
wire  useAlu;
wire  fn3_is_111;
wire  fn3_is_110;
wire  fn3_is_101;
wire  fn3_is_100;
wire  fn3_is_011;
wire  fn3_is_010;
wire  fn3_is_001;
wire  fn3_is_000;
wire  isJalr;
wire  isOpR;
wire  isOpI;
wire R1391 = (|rst) ; 
wire R1392 = ~(|rst) & (|ft0) & ~(|iack_i) ; 
wire R1393 = ~(|rst) & (|ft0) & (|iack_i) ; 
wire R1394 = ~(|rst) & ~(|ft0) & ~(|xt0) & ~(|xt1) & ~(|xt2) & ~(|xt3) ; 
wire R1395 = ( ir[14:12] == 3'b000 ) ; 
wire R1396 = ( ir[14:12] == 3'b001 ) ; 
wire R1397 = ( ir[14:12] == 3'b010 ) ; 
wire R1398 = ( ir[14:12] == 3'b011 ) ; 
wire R1399 = ( ir[14:12] == 3'b100 ) ; 
wire R1400 = ( ir[14:12] == 3'b101 ) ; 
wire R1401 = ( ir[14:12] == 3'b110 ) ; 
wire R1402 = ( ir[14:12] == 3'b111 ) ; 
wire R1403 = ( ir[6:4] == 7'b001 ) & ( ir[2:0] == 3'b011 ) ; 
wire R1404 = ( ir[6:4] == 7'b011 ) & ( ir[2:0] == 3'b011 ) ; 
wire R1405 = ~(|rst) & (|xt0) & (|isOpI) ; 
wire R1406 = ~(|rst) & (|xt1) & (|isOpI) ; 
wire R1407 = ~(|rst) & (|xt2) & (|isOpI) ; 
wire R1408 = (|useAlu) & (|fn3_is_000) ; 
wire R1409 = (|useAlu) & (|fn3_is_001) ; 
wire R1410 = (|useAlu) & (|fn3_is_010) ; 
wire R1411 = (|useAlu) & (|fn3_is_011) ; 
wire R1412 = (|useAlu) & (|fn3_is_100) ; 
wire R1413 = (|useAlu) & (|fn3_is_101) & ~(|ir[30]) ; 
wire R1414 = (|useAlu) & (|fn3_is_101) & (|ir[30]) ; 
wire R1415 = (|useAlu) & (|fn3_is_110) ; 
wire R1416 = (|useAlu) & (|fn3_is_111) ; 
wire R1417 = (|useAlu) & (|ir[3]) ; 
wire R1418 = ~(|rst) & (|xt0) & (|isOpR) ; 
wire R1419 = ~(|rst) & (|xt1) & (|isOpR) ; 
wire R1420 = ~(|rst) & (|xt2) & (|isOpR) ; 
wire R1421 = ~(|rst) & (|xt3) & (|isOpR) ; 
wire R1422 = (|useAlu2) & (|fn3_is_000) & ~(|ir[30]) ; 
wire R1423 = (|useAlu2) & (|fn3_is_000) & (|ir[30]) ; 
wire R1424 = (|useAlu2) & (|fn3_is_001) ; 
wire R1425 = (|useAlu2) & (|fn3_is_010) ; 
wire R1426 = (|useAlu2) & (|fn3_is_011) ; 
wire R1427 = (|useAlu2) & (|fn3_is_100) ; 
wire R1428 = (|useAlu2) & (|fn3_is_101) & ~(|ir[30]) ; 
wire R1429 = (|useAlu2) & (|fn3_is_101) & (|ir[30]) ; 
wire R1430 = (|useAlu2) & (|fn3_is_110) ; 
wire R1431 = (|useAlu2) & (|fn3_is_111) ; 
wire R1432 = (|useAlu2) & (|ir[3]) ; 
wire R1433 = ( ir[6:0] == 7'b1100111 ) ; 
wire R1434 = ~(|rst) & (|xt0) & (|isJalr) ; 
wire R1435 = ~(|rst) & (|xt1) & (|isJalr) ; 
wire R1436 = ~(|rst) & (|xt2) & (|isJalr) ; 
wire R1437 = ~(|rst) & (|xt3) & (|isJalr) ; 
wire  out1438 = R1391 ? 1 : 0 ; 
wire  out1439 = R1391 ? 1 : 0 ; 
wire  out1440 = R1392 ? 1 : 0 ; 
wire  out1441 = R1392 ? 1 : 0 ; 
wire  out1442 = R1392 ? 1 : 0 ; 
wire  out1443 = R1393 ? 1 : 0 ; 
wire  out1444 = R1393 ? 1 : 0 ; 
wire  out1445 = R1393 ? 1 : 0 ; 
wire  out1446 = R1393 ? 1 : 0 ; 
wire  out1447 = R1393 ? 1 : 0 ; 
wire  out1448 = R1394 ? 1 : 0 ; 
wire  out1449 = R1395 ? 1 : 0 ; 
wire  out1450 = R1396 ? 1 : 0 ; 
wire  out1451 = R1397 ? 1 : 0 ; 
wire  out1452 = R1398 ? 1 : 0 ; 
wire  out1453 = R1399 ? 1 : 0 ; 
wire  out1454 = R1400 ? 1 : 0 ; 
wire  out1455 = R1401 ? 1 : 0 ; 
wire  out1456 = R1402 ? 1 : 0 ; 
wire  out1457 = R1403 ? 1 : 0 ; 
wire  out1458 = R1404 ? 1 : 0 ; 
wire  out1459 = R1405 ? 1 : 0 ; 
wire  out1460 = R1405 ? 1 : 0 ; 
wire  out1461 = R1406 ? 1 : 0 ; 
wire  out1462 = R1406 ? 1 : 0 ; 
wire  out1463 = R1406 ? 1 : 0 ; 
wire  out1464 = R1407 ? 1 : 0 ; 
wire  out1465 = R1407 ? 1 : 0 ; 
wire  out1466 = R1407 ? 1 : 0 ; 
wire  out1467 = R1407 ? 1 : 0 ; 
wire  out1468 = R1407 ? 1 : 0 ; 
wire  out1469 = R1408 ? 1 : 0 ; 
wire  out1470 = R1409 ? 1 : 0 ; 
wire  out1471 = R1410 ? 1 : 0 ; 
wire  out1472 = R1410 ? 1 : 0 ; 
wire  out1473 = R1410 ? 1 : 0 ; 
wire  out1474 = R1411 ? 1 : 0 ; 
wire  out1475 = R1411 ? 1 : 0 ; 
wire  out1476 = R1411 ? 1 : 0 ; 
wire  out1477 = R1412 ? 1 : 0 ; 
wire  out1478 = R1413 ? 1 : 0 ; 
wire  out1479 = R1414 ? 1 : 0 ; 
wire  out1480 = R1414 ? 1 : 0 ; 
wire  out1481 = R1415 ? 1 : 0 ; 
wire  out1482 = R1415 ? 1 : 0 ; 
wire  out1483 = R1416 ? 1 : 0 ; 
wire  out1484 = R1417 ? 1 : 0 ; 
wire  out1485 = R1418 ? 1 : 0 ; 
wire  out1486 = R1418 ? 1 : 0 ; 
wire  out1487 = R1419 ? 1 : 0 ; 
wire  out1488 = R1419 ? 1 : 0 ; 
wire  out1489 = R1419 ? 1 : 0 ; 
wire  out1490 = R1420 ? 1 : 0 ; 
wire  out1491 = R1420 ? 1 : 0 ; 
wire  out1492 = R1421 ? 1 : 0 ; 
wire  out1493 = R1421 ? 1 : 0 ; 
wire  out1494 = R1421 ? 1 : 0 ; 
wire  out1495 = R1421 ? 1 : 0 ; 
wire  out1496 = R1421 ? 1 : 0 ; 
wire  out1497 = R1422 ? 1 : 0 ; 
wire  out1498 = R1423 ? 1 : 0 ; 
wire  out1499 = R1423 ? 1 : 0 ; 
wire  out1500 = R1423 ? 1 : 0 ; 
wire  out1501 = R1424 ? 1 : 0 ; 
wire  out1502 = R1425 ? 1 : 0 ; 
wire  out1503 = R1425 ? 1 : 0 ; 
wire  out1504 = R1425 ? 1 : 0 ; 
wire  out1505 = R1426 ? 1 : 0 ; 
wire  out1506 = R1426 ? 1 : 0 ; 
wire  out1507 = R1426 ? 1 : 0 ; 
wire  out1508 = R1427 ? 1 : 0 ; 
wire  out1509 = R1428 ? 1 : 0 ; 
wire  out1510 = R1429 ? 1 : 0 ; 
wire  out1511 = R1429 ? 1 : 0 ; 
wire  out1512 = R1430 ? 1 : 0 ; 
wire  out1513 = R1430 ? 1 : 0 ; 
wire  out1514 = R1431 ? 1 : 0 ; 
wire  out1515 = R1432 ? 1 : 0 ; 
wire  out1516 = R1433 ? 1 : 0 ; 
wire  out1517 = R1434 ? 1 : 0 ; 
wire  out1518 = R1434 ? 1 : 0 ; 
wire  out1519 = R1434 ? 1 : 0 ; 
wire  out1520 = R1434 ? 1 : 0 ; 
wire  out1521 = R1435 ? 1 : 0 ; 
wire  out1522 = R1435 ? 1 : 0 ; 
wire  out1523 = R1436 ? 1 : 0 ; 
wire  out1524 = R1436 ? 1 : 0 ; 
wire  out1525 = R1436 ? 1 : 0 ; 
wire  out1526 = R1437 ? 1 : 0 ; 
wire  out1527 = R1437 ? 1 : 0 ; 
wire  out1528 = R1437 ? 1 : 0 ; 
assign invB_en = out1506|out1503|out1500|out1475|out1472;
assign cflag_i = out1511|out1505|out1502|out1499|out1480|out1474|out1471;
assign and_en = out1514|out1512|out1483|out1481;
assign isJalr = out1516;
assign fn3_is_000 = out1449;
assign fn3_is_001 = out1450;
assign fn3_is_010 = out1451;
assign fn3_is_100 = out1453;
assign fn3_is_011 = out1452;
assign fn3_is_101 = out1454;
assign fn3_is_110 = out1455;
assign fn3_is_111 = out1456;
assign iadr_pc = out1443|out1440;
assign useAlu = out1467;
assign ra_ird = out1518|out1492|out1464;
assign jammed_o = out1448;
assign pc_alu = out1527;
assign pc_mbvec = out1439;
assign ir_idat = out1446;
assign lsh_en = out1501|out1470;
assign rdat_pc = out1519;
assign rsh_en = out1510|out1509|out1479|out1478;
assign rwe_o = out1520|out1494|out1466;
assign alua_rdat = out1524|out1488|out1462;
assign alub_imm12i = out1525|out1463;
assign sx32_en = out1515|out1484;
assign alub_rdat = out1491;
assign rdat_alu = out1493|out1465;
assign lts_en = out1504|out1473;
assign sum_en = out1528|out1498|out1497|out1469;
assign ltu_en = out1507|out1476;
assign xor_en = out1513|out1508|out1482|out1477;
assign ft0_o = out1526|out1496|out1468|out1442|out1438;
assign useAlu2 = out1495;
assign ra_ir1 = out1522|out1486|out1460;
assign ra_ir2 = out1489;
assign isOpI = out1457;
assign pc_pcPlus4 = out1445;
assign xt0_o = out1447;
assign xt1_o = out1517|out1485|out1459;
assign isiz_2 = out1444|out1441;
assign xt2_o = out1521|out1487|out1461;
assign isOpR = out1458;
assign xt3_o = out1523|out1490;
endmodule
